bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind u swap-pane -t -1
bind p swap-pane -t +1

bind-key C clear-history \; send-keys -t . C-l

set -sg escape-time 0
set -g mouse on

set-option -g history-limit 3000

set -g status-style "bg=default"
set -g status-right "#[fg=green,bg=default]#[fg=black,bg=green,bold] %H:%M "

set-option -g focus-events on

set-option -a terminal-features 'xterm-256color:RGB'
